stages:
  - test
  - build

# Cache des dépendances pour accélérer les jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/
    - backend/node_modules/

unit-tests:
  stage: test
  image: node:20-alpine
  script:
    - npm ci --legacy-peer-deps
    - npm run test
  artifacts:
    reports:
      junit: junit.xml
    when: always
  allow_failure: true

lint:
  stage: test
  image: node:20-alpine
  script:
    - npm ci --legacy-peer-deps
    - npm run lint
  allow_failure: true

typescript:
  stage: test
  image: node:20-alpine
  script:
    - npm ci --legacy-peer-deps
    - cd ./backend && npm ci
    - npm run type-check

# Job pour le build
build:
  stage: build
  image: node:20-alpine
  script:
    - npm ci --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 week
  only:
    - main
