import type { Metadata } from 'next'
import './globals.scss'
import Header from '@/components/ui/organisms/Header/Header'
import { lora, baskervville, merriweather } from './font'
import Footer from '@/components/ui/organisms/Footer/Footer'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${lora.variable} ${baskervville.variable} ${merriweather.variable}antialiased`}
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
