'use client'

import './globals.scss'
import type { Metadata } from 'next'
import { lora, baskervville, merriweather } from './font'
import Footer from '@/components/ui/organisms/Footer/Footer'
import { useEffect, useState } from 'react'
import Header from '@/components/ui/organisms/Header/Header'
import HeaderMobile from '@/components/ui/organisms/HeaderMobile/HeaderMobile'

// J'ai du enlever metadata car 'use client' ne l'autorise pas à vérifier si je garde
// le useEffect ici
// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }



export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {

    const [isMobile, setIsMobile] = useState(false)

    useEffect(() => {
      const checkIsMobile = () => {
        setIsMobile(window.innerWidth < 768)
      }
      
      checkIsMobile()
      window.addEventListener('resize', checkIsMobile)
      
      return () => window.removeEventListener('resize', checkIsMobile)
    }, [])
  
    return (
        <html lang="en">
            <body
                className={`${lora.variable} ${baskervville.variable} ${merriweather.variable}antialiased`}
            >
                {isMobile ? <HeaderMobile /> : <Header /> }
                {children}
                <Footer />
            </body>
        </html>
    )
}
